// Code generated by ddd-domain-gen, DO NOT EDIT.
package agent

import (
	"errors"
	"fmt"
	gouuid "github.com/satori/go.uuid"
	"reflect"
)

// Constructors ...

// New returns a guaranteed-to-be-valid Agent or an error
func New(uuid gouuid.UUID, name string) (*Agent, error) {
	if reflect.ValueOf(uuid).IsZero() {
		return nil, errors.New("missing UUID")
	}
	if reflect.ValueOf(name).IsZero() {
		return nil, errors.New("missing name")
	}
	a := &Agent{
		name: name,
		uuid: uuid,
	}
	return a, nil
}

// MustNew returns a guaranteed-to-be-valid Agent or panics
func MustNew(uuid gouuid.UUID, name string) *Agent {
	a, err := New(uuid, name)
	if err != nil {
		panic(err)
	}
	return a
}

// Marshalers ...

// UnmarshalFromRepository unmarshals Agent from the repository so that non-constructable
// private fields can still be initialized from (private) repository state
//
// Important: DO NEVER USE THIS METHOD EXCEPT FROM THE REPOSITORY
// Reason: This method initializes private state, so you could corrupt the domain.
func UnmarshalFromRepository(uuid gouuid.UUID, name string) *Agent {
	a := MustNew(uuid, name)
	return a
}

// Accessors ...

// Utilities ...

// Equal answers whether v is equivalent to a
// Always returns false if v is not a Agent
func (a Agent) Equal(v interface{}) bool {
	other, ok := v.(Agent)
	if !ok {
		return false
	}
	if a.uuid != other.uuid {
		return false
	}
	return a
}

// String implements the fmt.Stringer interface and returns the native format of Agent
func (a Agent) String() string {
	return fmt.Sprintf("%s ", a.name)
}
