// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package agent

import (
	"fmt"
)

// Equal answers whether v is equivalent to a.
// Always returns false if v is not a Agent.
func (a Agent) Equal(v interface{}) bool {
	a2, ok := v.(Agent)
	if !ok {
		return false
	}
	if a.uuid != a2.uuid {
		return false
	}
	return true
}

// String returns the "native" format of Agent. Implements the fmt.Stringer interface.
func (a Agent) String() string {
	return fmt.Sprintf("%v", a.name)
}
