// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package party

import (
	"fmt"
)

// Equal answers whether v is equivalent to p.
// Always returns false if v is not a Party.
func (p Party) Equal(v interface{}) bool {
	p2, ok := v.(Party)
	if !ok {
		return false
	}
	if p.uuid != p2.uuid {
		return false
	}
	return true
}

// String returns the "native" format of Party. Implements the fmt.Stringer interface.
func (p Party) String() string {
	return fmt.Sprintf("%v %v", p.pType, p.name)
}
