// Code generated by ddd-domain-gen, DO NOT EDIT.
package campaign

// Generators ...

// New returns a guaranteed-to-be-valid Campaign or an error
func New(uuid string, name string, priority priority) (*Campaign, error) {
	c := &Campaign{
		name:     name,
		priority: priority,
		uuid:     uuid,
	}
	return c, nil
}

// MustNew returns a guaranteed-to-be-valid Campaign or panics
func MustNew(uuid string, name string, priority priority) *Campaign {
	c, err := New(uuid, name, priority)
	if err != nil {
		panic(err)
	}
	return c
}

// Marshalers ...

// UnmarshalFromRepository unmarshals Campaign from the repository so that non-constructable
// private fields can still be initialized from (private) repository state
//
// Important: DO NEVER USE THIS METHOD EXCEPT FROM THE REPOSITORY
// Reason: This method initializes private state, so you could corrupt the domain.
func UnmarshalFromRepository(uuid string, name string, priority priority) *Campaign {
	c := MustNew(uuid, name, priority)
	return c
}
