// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package campaign

// Uuid returns the value of uuid.
func (c Campaign) Uuid() string {
	return c.uuid
}

// Name returns the value of name.
func (c Campaign) Name() string {
	return c.name
}

// Priority returns the value of priority.
func (c Campaign) Priority() priority {
	return c.priority
}
