{ pkgs, src, excludes ? [ ] }:
with pkgs;
(import ./pre-commit-src.nix).run {

  inherit src;
  default_stages = [ "manual" "push" ];

  excludes = [
  ] ++ excludes;

  settings = {
  };

  hooks = {

    shellcheck.enable = true;

    shfmt = {
      enable = true;
      name = "shfmt";
      description = "Format Shell files";
      entry = "${shfmt}/bin/shfmt -w -l";
      types = [ "shell" ];
    };

    generate = {
      enable = true;
      name = "generate";
      description = "generate autogenerated files";
      entry = "${just}/bin/just generate";
      pass_filenames = false;
      always_run = true;
    };
  };

}
