// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package livecall

import (
	"fmt"
	"github.com/blaggacao/vicidial-go/internal/livecalls/domain/party"
)

// Equal answers whether v is equivalent to l.
// Always returns false if v is not a Livecall.
func (l Livecall) Equal(v interface{}) bool {
	l2, ok := v.(Livecall)
	if !ok {
		return false
	}
	if l.uuid != l2.uuid {
		return false
	}
	return true
}

// Lead returns the value of lead.
func (l Livecall) Lead() party.Party {
	return l.lead
}

// String returns the "native" format of Livecall. Implements the fmt.Stringer interface.
func (l Livecall) String() string {
	return fmt.Sprintf("%v %v", l.lead, l.agentOrService)
}

// AgentOrService returns the value of agentOrService.
func (l Livecall) AgentOrService() party.Party {
	return l.agentOrService
}
