// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package scheduler

import (
	"fmt"
	"github.com/xoe-labs/vicidial-go/internal/scheduling/domain/campaign"
)

// Equal answers whether v is equivalent to s.
// Always returns false if v is not a Scheduler.
func (s Scheduler) Equal(v interface{}) bool {
	s2, ok := v.(Scheduler)
	if !ok {
		return false
	}
	if s.uuid != s2.uuid {
		return false
	}
	return true
}

// String returns the "native" format of Scheduler. Implements the fmt.Stringer interface.
func (s Scheduler) String() string {
	return fmt.Sprintf("%v", s.name)
}

// CoveredCampaigns returns the value of coveredCampaigns.
func (s Scheduler) CoveredCampaigns() []campaign.Campaign {
	return s.coveredCampaigns
}
