// Code generated by ddd-domain-gen, DO NOT EDIT.
package call

import party "github.com/xoe-labs/vicidial-go/internal/common/party"

// Generators ...

// New returns a guaranteed-to-be-valid Call or an error
func New(meta meta, remoteParty party.RemoteParty, localParty party.LocalParty) (*Call, error) {
	c := &Call{
		localParty:  localParty,
		meta:        meta,
		remoteParty: remoteParty,
	}
	return c, nil
}

// MustNew returns a guaranteed-to-be-valid Call or panics
func MustNew(meta meta, remoteParty party.RemoteParty, localParty party.LocalParty) *Call {
	c, err := New(meta, remoteParty, localParty)
	if err != nil {
		panic(err)
	}
	return c
}

// Marshalers ...

// UnmarshalFromRepository unmarshals Call from the repository so that non-constructable
// private fields can still be initialized from (private) repository state
//
// Important: DO NEVER USE THIS METHOD EXCEPT FROM THE REPOSITORY
// Reason: This method initializes private state, so you could corrupt the domain.
func UnmarshalFromRepository(meta meta, remoteParty party.RemoteParty, localParty party.LocalParty) *Call {
	c := MustNew(meta, remoteParty, localParty)
	return c
}
