bin/AST_manager_send.pl:135:SELECT COUNT(*) from vicidial_manager where server_ip = ?/* '" . $conf{VARserver_ip} . "' */ and status = 'NEW';
bin/AST_manager_send.pl:141:SELECT COUNT(*) from vicidial_manager where server_ip = ?/* '" . $conf{VARserver_ip} . "' */ and status = 'QUEUE';
bin/AST_manager_send.pl:151:UPDATE vicidial_manager set status='QUEUE' where server_ip = ?/* '" . $conf{VARserver_ip} . "' */ and status = 'NEW' order by man_id LIMIT 1;
bin/AST_manager_send.pl:167:SELECT man_id,uniqueid,entry_date,status,response,server_ip,channel,action,callerid,cmd_line_b,cmd_line_c,cmd_line_d,cmd_line_e,cmd_line_f,cmd_line_g,cmd_line_h,cmd_line_i,cmd_line_j,cmd_line_k FROM vicidial_manager where server_ip = ?/* '" . $conf{VARserver_ip} . "' */ and status = 'QUEUE' order by man_id LIMIT 1
bin/AST_manager_send.pl:200:SELECT COUNT(*) FROM vicidial_manager where server_ip = ?/* '" . $conf{VARserver_ip} . "' */ and callerid=?/* '" . $vdm->{callerid} . "' */ and status = 'DEAD'
bin/AST_manager_send.pl:264:UPDATE vicidial_manager set status='SENT' where man_id=?/* '" . $vdm->{man_id} . "' */
bin/AST_manager_send.pl:273:UPDATE vicidial_manager set status='DEAD' where man_id=?/* '" . $vdm->{man_id} . "' */ and cmd_line_d!='Exten: 8309' and cmd_line_d!='Exten: 8310';
bin/AST_manager_send.pl:369:SELECT server_id,server_description,server_ip,active,asterisk_version,max_vicidial_trunks,telnet_host,telnet_port,ASTmgrUSERNAME,ASTmgrSECRET,ASTmgrUSERNAMEupdate,ASTmgrUSERNAMElisten,ASTmgrUSERNAMEsend,local_gmt,voicemail_dump_exten,answer_transfer_agent,ext_context,sys_perf_log,vd_server_logs,agi_output,vicidial_balance_active,balance_trunks_offlimits,recording_web_link,alt_server_ip,active_asterisk_server,generate_vicidial_conf,rebuild_conf_files,outbound_calls_per_second,sysload,channels_total,cpu_idle_percent,disk_usage,sounds_update,vicidial_recording_limit,carrier_logging_active,vicidial_balance_rank,rebuild_music_on_hold,active_agent_login_server,conf_secret FROM servers where server_ip = ?/* '" . $serverip ."' */;
bin/AST_manager_listen_AMI2.pl:129:SELECT telnet_host,telnet_port,ASTmgrUSERNAME,ASTmgrSECRET,ASTmgrUSERNAMEupdate,ASTmgrUSERNAMElisten,ASTmgrUSERNAMEsend,max_vicidial_trunks,answer_transfer_agent,local_gmt,ext_context,vd_server_logs,asterisk_version FROM servers where server_ip = ?/* $server_ip */;
bin/AST_manager_listen_AMI2.pl:331:SELECT vd_server_logs FROM servers where server_ip = ?/* $server_ip */;
bin/AST_manager_listen_AMI2.pl:585:UPDATE vicidial_manager set status='DEAD', channel=?/* $event_hash{'Channel'} */ where server_ip = ?/* $server_ip */ and uniqueid = ?/* $event_hash{'Uniqueid'} */ and cmd_line_d!='Exten: 8309' and cmd_line_d!='Exten: 8310';
bin/AST_manager_listen_AMI2.pl:623:UPDATE vicidial_manager set status='SENT', channel=?/* $event_hash{'Channel'} */, uniqueid = ?/* $event_hash{'Uniqueid'} */ where server_ip = ?/* $event_hash{'ServerIP'} */ and callerid = ?/* $call_id */
bin/AST_manager_listen_AMI2.pl:632:UPDATE vicidial_manager set status='UPDATED', channel=?/* $event_hash{'Channel'} */, uniqueid = ?/* $event_hash{'Uniqueid'} */ where server_ip = ?/* $event_hash{'ServerIP'} */ and callerid = ?/* $call_id */ and status != 'NEW'
bin/AST_manager_listen_AMI2.pl:675:UPDATE vicidial_manager set status='UPDATED', channel=?/* $event_hash{'Channel'} */, uniqueid = ?/* $event_hash{'Uniqueid'} */ where server_ip = ?/* $event_hash{'ServerIP'} */ and callerid = ?/* $call_id */
bin/AST_manager_listen_AMI2.pl:710:INSERT INTO vicidial_dtmf_log SET dtmf_time=NOW(),channel=?/* $event_hash{'Channel'} */,server_ip=?/* $event_hash{'ServerIP'} */,uniqueid=?/* $event_hash{'Uniqueid'} */,digit=?/* $event_hash{'Digit'} */,direction=?/* $event_hash{'Direction'} */,state='Begin'
bin/AST_manager_listen_AMI2.pl:759:INSERT INTO vicidial_dtmf_log SET dtmf_time=NOW(),channel=?/* $event_hash{'Channel'} */,server_ip=?/* $event_hash{'ServerIP'} */,uniqueid=?/* $event_hash{'Uniqueid'} */,digit=?/* $event_hash{'Digit'} */,direction=?/* $event_hash{'Direction'} */,state='End'
bin/AST_manager_kill_hung_congested.pl:121:SELECT vd_server_logs FROM servers where server_ip = ?/* $VARserver_ip */;
bin/AST_manager_kill_hung_congested.pl:139:SELECT channel FROM live_sip_channels where server_ip = ?/* $server_ip */ and extension = 'CONGEST' and channel LIKE "Local%" LIMIT 99
bin/AST_manager_kill_hung_congested.pl:168:INSERT INTO vicidial_manager values('','',?/* $now_date */,'NEW','N',?/* $server_ip */,'','Hangup',?/* $KCqueryCID */,'Channel: $congest_kill[$i]','','','','','','','','','')
bin/AST_manager_kill_hung_congested.pl:188:SELECT channel FROM live_sip_channels where server_ip = ?/* $server_ip */ and extension = 'CONGEST' and channel LIKE "Local%" LIMIT 99
bin/AST_manager_kill_hung_congested.pl:217:INSERT INTO vicidial_manager values('','',?/* $now_date */,'NEW','N',?/* $server_ip */,'','Hangup',?/* $KCqueryCID */,'Channel: $congest_kill[$i]','','','','','','','','','')
bin/AST_manager_kill_hung_congested.pl:238:SELECT channel FROM live_sip_channels where server_ip = ?/* $server_ip */ and extension = 'CONGEST' and channel LIKE "Local%" LIMIT 99
bin/AST_manager_kill_hung_congested.pl:267:INSERT INTO vicidial_manager values('','',?/* $now_date */,'NEW','N',?/* $server_ip */,'','Hangup',?/* $KCqueryCID */,'Channel: $congest_kill[$i]','','','','','','','','','')
bin/AST_manager_kill_hung_congested.pl:289:SELECT channel FROM live_sip_channels where server_ip = ?/* $server_ip */ and extension = 'CONGEST' and channel LIKE "Local%" LIMIT 99
bin/AST_manager_kill_hung_congested.pl:319:INSERT INTO vicidial_manager values('','',?/* $now_date */,'NEW','N',?/* $server_ip */,'','Hangup',?/* $KCqueryCID */,'Channel: $congest_kill[$i]','','','','','','','','','')
bin/AST_update_AMI2.pl:154:SELECT telnet_host,telnet_port,ASTmgrUSERNAME,ASTmgrSECRET,ASTmgrUSERNAMEupdate,ASTmgrUSERNAMElisten,ASTmgrUSERNAMEsend,max_vicidial_trunks,answer_transfer_agent,local_gmt,ext_context,vd_server_logs,asterisk_version FROM servers where server_ip = ?/* $server_ip */;
bin/AST_update_AMI2.pl:194:SELECT COUNT(*) FROM server_updater where server_ip=?/* $server_ip */;
bin/AST_update_AMI2.pl:205:INSERT INTO server_updater set server_ip=?/* $server_ip */, last_update=NOW();
bin/AST_update_AMI2.pl:569:UPDATE server_updater set last_update=NOW() where server_ip=?/* $server_ip */
bin/AST_update_AMI2.pl:974:DELETE FROM live_sip_channels where \n\t(" . $client_delete_sql . " )
bin/AST_update_AMI2.pl:984:DELETE FROM live_channels where \n\t(" . $trunk_delete_sql . " )
bin/AST_update_AMI2.pl:1017:INSERT IGNORE INTO $cid_channels_recent (caller_id_name, connected_line_name, call_date, channel, dest_channel, linkedid, dest_uniqueid, uniqueid) values \n\t
bin/AST_update_AMI2.pl:1037:DELETE pc1 FROM parked_channels pc1, parked_channels pc2 WHERE pc1.parked_time < pc2.parked_time AND pc1.parked_time <> pc2.parked_time AND pc1.channel = pc2.channel AND pc1.server_ip=?/* $server_ip */ and pc2.server_ip=?/* $server_ip */
bin/AST_update_AMI2.pl:1042:SELECT channel,extension,parked_time,UTC_TIMESTAMP(parked_time),channel_group FROM parked_channels where server_ip = ?/* $server_ip */ order by channel desc, parked_time desc;
bin/AST_update_AMI2.pl:1100:DELETE FROM parked_channels WHERE (" . $park_delete_sql . ") and server_ip=?/* $server_ip */
bin/AST_update_AMI2.pl:1217:UPDATE servers SET sysload=?/* $server_load */, channels_total=?/* $channel_counts->{'total'} */, cpu_idle_percent=?/* $cpu_idle_percent */, disk_usage=?/* $disk_usage */ where server_ip=?/* $server_ip */;
bin/AST_update_AMI2.pl:1231:INSERT INTO server_performance (start_time, server_ip, sysload, freeram, usedram, processes, channels_total, trunks_total, clients_total, clients_zap, clients_iax, clients_local, clients_sip, live_recordings, cpu_user_percent, cpu_system_percent, cpu_idle_percent, disk_reads, disk_writes) values( NOW(), ?/* $server_ip */, ?/* $server_load */, ?/* $mem_free */, ?/* $mem_used */, ?/* $num_processes */, ?/* $channel_counts->{'total'} */, ?/* $channel_counts->{'trunks'} */, ?/* $channel_counts->{'clients'} */, ?/* $channel_counts->{'dahdi'} */, ?/* $channel_counts->{'iax'} */, ?/* $channel_counts->{'local'} */, ?/* $channel_counts->{'sip'} */, '0', ?/* $cpu_user_percent */, ?/* $cpu_sys_percent */, ?/* $cpu_idle_percent */, ?/* $reads */, ?/* $writes */)
bin/AST_update_AMI2.pl:1246:SELECT sys_perf_log,vd_server_logs FROM servers where server_ip=?/* $server_ip */;
bin/AST_update_AMI2.pl:1264:SELECT extension, protocol FROM phones where server_ip=?/* $server_ip */ and phone_type NOT LIKE "%trunk%"
bin/AST_update_AMI2.pl:1315:SELECT channel,extension FROM live_channels where server_ip=?/* $server_ip */;
bin/AST_update_AMI2.pl:1324:SELECT channel,extension FROM live_sip_channels where server_ip=?/* $server_ip */;
bin/AST_manager_sip_AMI2.pl:116:SELECT telnet_host,telnet_port,ASTmgrUSERNAME,ASTmgrSECRET,ASTmgrUSERNAMEupdate,ASTmgrUSERNAMElisten,ASTmgrUSERNAMEsend,max_vicidial_trunks,answer_transfer_agent,local_gmt,ext_context,vd_server_logs,asterisk_version FROM servers where server_ip = ?/* $server_ip */;
bin/AST_manager_sip_AMI2.pl:321:SELECT vd_server_logs FROM servers where server_ip = ?/* $server_ip */;
bin/AST_manager_sip_AMI2.pl:575:INSERT INTO vicidial_sip_event_log SET caller_code =?/* $call_id */, channel=?/* $event_hash{'Channel'} */, server_ip=?/* $event_hash{'ServerIP'} */, uniqueid=?/* $event_hash{'Uniqueid'} */, sip_call_id=?/* $event_hash{'SIPCallID'} */, event_date = FROM_UNIXTIME( $event_hash{'Timestamp'} ), sip_event = 'INVITE'
bin/AST_manager_sip_AMI2.pl:582:INSERT INTO vicidial_sip_event_recent SET caller_code =?/* $call_id */, channel=?/* $event_hash{'Channel'} */, server_ip=?/* $event_hash{'ServerIP'} */, uniqueid=?/* $event_hash{'Uniqueid'} */, invite_date = FROM_UNIXTIME( $event_hash{'Timestamp'} )
bin/AST_manager_sip_AMI2.pl:626:INSERT INTO vicidial_sip_event_log SET caller_code =?/* $call_id */, channel=?/* $event_hash{'Channel'} */, server_ip=?/* $event_hash{'ServerIP'} */, uniqueid=?/* $event_hash{'Uniqueid'} */, sip_call_id=?/* $event_hash{'SIPCallID'} */, event_date = FROM_UNIXTIME( $event_hash{'Timestamp'} ), sip_event = ?/* $event_hash{'Response'} */
bin/AST_manager_sip_AMI2.pl:635:UPDATE vicidial_sip_event_recent SET first_100_date = IF( first_100_date IS NULL, FROM_UNIXTIME( $event_hash{'Timestamp'} ), first_100_date), last_100_date = FROM_UNIXTIME( $event_hash{'Timestamp'} ) where caller_code = ?/* $call_id */
bin/AST_manager_sip_AMI2.pl:639:UPDATE vicidial_sip_event_recent SET first_180_date = IF( first_180_date IS NULL, FROM_UNIXTIME( $event_hash{'Timestamp'} ), first_180_date), last_180_date = FROM_UNIXTIME( $event_hash{'Timestamp'} ) where caller_code = ?/* $call_id */
bin/AST_manager_sip_AMI2.pl:643:UPDATE vicidial_sip_event_recent SET first_183_date = IF( first_183_date IS NULL, FROM_UNIXTIME( $event_hash{'Timestamp'} ), first_183_date), last_183_date = FROM_UNIXTIME( $event_hash{'Timestamp'} ) where caller_code = ?/* $call_id */
bin/AST_manager_sip_AMI2.pl:647:UPDATE vicidial_sip_event_recent SET 200_date = FROM_UNIXTIME( $event_hash{'Timestamp'} ) where caller_code = ?/* $call_id */
bin/AST_manager_sip_AMI2.pl:651:UPDATE vicidial_sip_event_recent SET error_date = FROM_UNIXTIME( $event_hash{'Timestamp'} ) where caller_code = ?/* $call_id */
