name: Docker
on:
  push:
    branch: master
    tags: ['v*']
  pull_request:
  release:
    types: [published,released]

jobs:
  multi:
    name: "Multi"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the container image
        uses: docker/build-push-action@v3
        with:
          repository: vicidial-go

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        if: github.event_name == 'release' || github.event_name == 'push'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: blaggacao/vicidial-go/vicidial-go
          tag_with_ref: true

      # - name: check docker hub credentials
      #   id: check_dockerhub_credentials
      #   if: github.event_name == 'release' || github.event_name == 'push'
      #   env:
      #     docker_username: ${{ secrets.docker_username }}
      #     docker_password: ${{ secrets.docker_password }}
      #   run: |
      #     if [ "${docker_username}" == "" ]; then
      #       echo "missing username"
      #       echo "##[set-output name=missingsecrets;]$(echo yes)"
      #     elif [ "${docker_password}" == "" ]; then
      #       echo "missing password"
      #       echo "##[set-output name=missingsecrets;]$(echo yes)"
      #     else
      #       echo "all secrets present"
      #       echo "##[set-output name=missingsecrets;]$(echo no)"
      #     fi

      # - name: push to docker hub
      #   if: |
      #     (github.event_name == 'release' || github.event_name == 'push') &&
      #     contains(steps.check_dockerhub_credentials.outputs.missingsecrets, 'no')
      #   uses: docker/build-push-action@v3
      #   with:
      #     username: ${{ secrets.docker_username }}
      #     password: ${{ secrets.docker_password }}
      #     repository: blaggacao/vicidial-go
      #     tag_with_ref: true
